-- NÃO crie usuários inserindo diretamente em auth.users.
--
-- O script anterior continha senhas de equipe no repositório e alterava senhas
-- existentes. Ele foi removido por segurança.
--
-- Procedimento seguro:
-- 1. Em Supabase Dashboard > Authentication > Users, convide cada pessoa.
-- 2. Cada pessoa define a própria senha pelo e-mail recebido.
-- 3. O trigger em setup_isolated_tenants.sql cria o perfil como Operador.
-- 4. Promova somente os administradores necessários no SQL Editor, por exemplo:
--
-- UPDATE public.perfis
-- SET perfil = 'Administrador'
-- WHERE email = 'administrador@empresa.com';
--
-- Nunca versione senhas, chaves service_role ou tokens neste repositório.
